name: C/C++ CI Style Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  StyleCheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format
    - name: Run clang-format
      run: make style

  Tests:
    needs: StyleCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: make test